### ISSUE TITLE
[BUG][fajita] possible broken mount points

### ISSUE THREAD

**Issue by sreehax** [sailfish-oneplus6/sf-enchilada#10]
I have observed multiple different bugs in the fajita build when i try to run it. First off, vibration does not work during normal use such as alarms, typing, or getting calls, and this is confirmed when i try the CSD Tool testing thing. Second, i think i can connect to wifi, but i get no internet and i can't access ipv6 or ipv4 sites and signing into the jolla store obviously doesn't work as a result. Third, i cannot set a developer mode password to gain root access, so i couldn't gain root access to get logs, so i had to drop in an suid binary and privilege escalate myself to get root. Finally, it seems that a telnet server is not started on port 2323. These are only the bugs i have noticed, there are possibly more.
**journalctl output**
Both the journalctl and logcat output are available here:
[https://gist.github.com/sreehax/1da4b17aac57835f85abc10acf91c3b3](https://gist.github.com/sreehax/1da4b17aac57835f85abc10acf91c3b3)

**logcat output**
see above

**Comment by DeltoidDelta** [comment]
``
loading /vendor/firmware_mnt
/image/a630_sqe.fw failed with error -13
subsys-pil-tz soc:qcom,kgsl-hyp: loading /vendor/firmware_mnt/image/a630_zap.mdt failed with error
 -13
Feb 22 15:45:22 OnePlus6T udisksctl-user[4832]: Error creating textual authentication agent: Error opening current controlling terminal for the process (`/dev/tty'): No such device or address (polkit-error-quark, 0)
Feb 22 15:45:22 OnePlus6T udisksctl-user[4832]: Error mounting /dev/sda7: GDBus.Error:org.freedesktop.UDisks2.Error.NotAuthorizedCanObtain: Not authorized to perform operation
/proprietary/commonsys-intf/adsprpc/src/apps_std_imp.c:728:Error 45: fopen failed for /mnt/vendor/mnt/vendor/persist/sensors/registry/temp.json. (No such file or directory)
``

I see lots of vendor issues, possibly from missing vendor files. Did you flash LOS 16 correctly (on both slots) before flashing SFOS?

**Comment by sreehax** [comment]
I only flashed LOS 16 on slot A, and this was all that was required in the past and according to flashing instructions.

**Comment by calebccff** [comment]
@sreehax please upload the output of `systemctl --failed` and `mount`

**Comment by sreehax** [comment]
Ok here is the output of both:
[https://gist.github.com/sreehax/e3bc0f8b85fee530709acdeab43f6c63](https://gist.github.com/sreehax/e3bc0f8b85fee530709acdeab43f6c63)

**Comment by sreehax** [comment]
whatever it is it got fixed

**Comment by calebccff** [comment]
Issue seemed to be a rough build due to having to play around with git repos / branches when switching from building for Enchilada to building for Fajita.
