### ISSUE TITLE
[Support][OnePlus 6T 256GB]

### ISSUE THREAD

**Issue by samweisgamdschie** [sailfish-oneplus6/sf-enchilada#12]
Hello!

I read different information about the support of OnePlus 6T 256GB (https://www.gsmarena.com/oneplus_6t-9350.php). Can you clear out if it is supported to install and use SailfishOS with it? I have already ordered one and like to use SailfishOS on it.

Many thanks in advance

**Comment by calebccff** [comment]
Yes the OnePlus 6T is supported!

**Comment by samweisgamdschie** [comment]
Now i have got my brand new oneplus 6T and I am preparing to get SailfishOS running on it. According to flashing.md, at step 3 says
_Dirty flash Lineage OS 16.0, grab the latest nightly: enchilada :: fajita._
but there is no LOS 16.0 image downloadable. I only find v17 images. But flashing an v17 image means I have to upgrade the installed OxygenOS from 9 to 10.

On the other hand I found https://github.com/sailfish-oneplus6/android_device_oneplus_fajita, with a default branch with LOS 16.

So my question is, which of the following way is the one to go/supported:
* Upgrade OxygenOS from 9 to 10 -> Flash LOS 17 -> Flash SFOS
* Flash your custom LOS 16 from https://github.com/sailfish-oneplus6/android_device_oneplus_fajita -> Flash SFOS
* A third variant, I haven't found yet.

Again, many thanks in advance

**Comment by calebccff** [comment]
It looks like lineage OS 16 is no longer officially supported on the OnePlus 6 - You can find mirrors with a Google...

You won't be able to do much with a modified device repo - the repo you link to is outdated and just modified source used to compile sailfish OS.

**Comment by samweisgamdschie** [comment]
But is it possible to use your version of SFOS together with LOS17? To do the same steps but only with LOS17?

I have to say I flirt with /e/ and they have an official pie version. Is it possible flash SFOS with /e/ or should I stay with LOS (if so, with which version)?

**Comment by calebccff** [comment]
> But is it possible to use your version of SFOS together with LOS17? To do the same steps but only with LOS17?

From the guide: "*Slot A MUST be running LOS 16 before Sailfish installation*"

> I have to say I flirt with /e/ and they have an official pie version. Is it possible flash SFOS with /e/ or should I stay with LOS (if so, with which version)?

I have not tested and won't support anything except LOS 16
