### ISSUE TITLE
 /boot/hybris-boot.img;5f83511e: cpio: open failed - File exists

### ISSUE THREAD

**Issue by taskforpid** [sailfish-oneplus6/sf-enchilada#13]
build_all_packages --version

The following 3 NEW packages are going to be installed:
  droid-hal-enchilada-img-boot droid-hal-enchilada-img-recovery droid-hal-enchilada-kernel

3 new packages to install.
Overall download size: 0 B. Already cached: 40.2 MiB. After the operation, additional 45.3 MiB will be used.
Continue? [y/n/...? shows all options] (y): y
Installation of droid-hal-enchilada-img-boot-0.0.6-202010111622.armv7hl failed:
Error: Subprocess failed. Error: RPM failed: error: unpacking of archive failed on file /boot/hybris-boot.img;5f83511e: cpio: open failed - File exists
error: droid-hal-enchilada-img-boot-0.0.6-202010111622.armv7hl: install failed

Abort, retry, ignore? [a/r/i] (a): a
Problem occurred during or after installation or removal of packages:
Installation aborted by user
NOTICE: No tags describe the HEAD, will not fix package version.
error: Failed build dependencies:
    droid-hal-enchilada-img-boot is needed by droid-hal-version-enchilada-0.0.1-202010111838.armv7hl
    droid-hal-enchilada-img-recovery is needed by droid-hal-version-enchilada-0.0.1-202010111838.armv7hl
    droid-hal-enchilada-kernel is needed by droid-hal-version-enchilada-0.0.1-202010111838.armv7hl
    droid-hal-kernel is needed by droid-hal-version-enchilada-0.0.1-202010111838.armv7hl
Building target platforms: armv7hl-meego-linux
Building for target armv7hl-meego-linux

And this command is not helped:
sb2 -t $VENDOR-$DEVICE-$PORT_ARCH -m sdk-install -R zypper in ...

**Comment by calebccff** [comment]
Hiya, sorry I hadn't replied to your email it's been a busy day. Can you provide some more details about your environment?

Also try running
```
mka mrproper
mka hybris-hal
```
From habuild, and then
```
bp -c
```
From platform SDK.

**Comment by taskforpid** [comment]
Ubuntu 20.04.1 LTS fresh and minimal install with gnome3
And i use full your guide with fixed mistakes like:
.hadk.env
export ANDROID_ROOT="/data/sfos/hadk"
.bashrc
export ANDROID_ROOT="$HOME/Sailfish/src"
.mersdk.profile
export ANDROID_ROOT=$HOME/sfos/hadk
Or this is not mistakes?

Building hal, configs and mw works fine but 
bp -v   
install filed

And if i run:
build_all_packages -i

i can see
Error <creator>[10/12 00:46:48] : Command 'modprobe' is not available.

**Comment by JamiKettunen** [comment]
`Error [10/12 00:46:48] : Command 'modprobe' is not available.`
Platform SDK is still broken and missing stuff, as per usual: `sudo zypper in kmod`

To fix `error: unpacking of archive failed on file /boot/hybris-boot.img;5f83511e: cpio: open failed - File exists`:
```bash
pushd $ANDROID_ROOT/rpm/dhd
curl https://github.com/sailfishos-oneplus5/droid-hal-device/commit/f95c839f7be994d2020ccf877adad118d04e1d9a.patch | patch -p1 -f
popd
bp -dv
```

Let's hope SFOS 3.4 platform SDK chroot fixes all this nonsense considering the plan is to drop [OBS](https://build.sailfishos.org/) entirely at some point...

**Comment by taskforpid** [comment]
thank you! 
i've got success
