### ISSUE TITLE
[BUG] Cannot recieve incoming SMS on OnePlus 6T fajita.

### ISSUE THREAD

**Issue by sreehax** [sailfish-oneplus6/sf-enchilada#6]
**Describe the bug**
I have a T-Mobile US sim card in sim card slot 1, and no sim card in slot 2. I am able to send sms messages, make outgoing calls, and receive outgoing calls with no issue. 

**journalctl output**
My entire journalctl -b output and logcat output are visible here: [https://gist.github.com/sreehax/071cc4125261e00c3c1a5dae6afdc7ed](https://gist.github.com/sreehax/071cc4125261e00c3c1a5dae6afdc7ed)

**logcat output**
see above.

**Comment by calebccff** [comment]
The only relevant line I can see is
```
Feb 08 15:42:23 OnePlus6T ofonod[4015]: sms sending failed, retry
```

Is it possible that this is just due to poor signal?

**Comment by sreehax** [comment]
yeah looks like i just have horrible cell signal here, probably because of a lack of the volte/vowifi i'm used to

**Comment by sreehax** [comment]
nothing much can be done then i guess

**Comment by calebccff** [comment]
I'll leave the issue open until you can check somewhere with a better signal

**Comment by sreehax** [comment]
I got better signal at school and it still doesn't work. here are the logs: https://drive.google.com/folderview?id=12rydIVPPhFs_A9wyHn9FXdtkFm01Jd0D

**Comment by sreehax** [comment]
i had near full bars of 4G

**Comment by sreehax** [comment]
Also getting a data signal (even 3G) seems a bit iffy. Hopefully the logs can help

**Comment by DeltoidDelta** [comment]
Resolved: setting the correct APN for T-Mobile using this guide, https://www.t-mobile.com/support/devices/not-sold-by-t-mobile/byod-t-mobile-data-and-apn-settings#subhead1.

**Comment by calebccff** [comment]
Closing as solved!
