### ISSUE TITLE
[BUG] screen wake issue [enchilada/fajita]

### ISSUE THREAD

**Issue by sreehax** [sailfish-oneplus6/sf-enchilada#8]
**Describe the bug**
I tried to turn on the screen with the power button as usual but the screen didn't turn on one time until several seconds later and several button presses.

**journalctl output**
Both the journalctl -b and logcat output are available at [https://gist.github.com/sreehax/733bbe8cdc94f2bc93f6891c8b4baf21](https://gist.github.com/sreehax/733bbe8cdc94f2bc93f6891c8b4baf21).

**logcat output**
see above.

**Comment by calebccff** [comment]
This issue is [known about](https://github.com/sailfish-oneplus6/sf-enchilada/releases) - thanks for the logs, will look into this.

**Comment by sreehax** [comment]
Was this fixed in the recent kernel config change?

**Comment by calebccff** [comment]
Untested but in theory it shouldn't be an issue anymore.
